
Q3::
A try-catch block is used to handle exceptions that are thrown within the try block.
The catch block contains the code that will be executed if an exception is thrown.

A try-throw-catch block is similar, but in this case the throw statement is used explicitly within
the try block to throw an exception, rather than the exception being thrown implicitly by the code.
The catch block would then handle the exception that was thrown explicitly.

In general try-catch is used to handle the exception that occurs during the execution of the try block where as
try-throw-catch can be used to handle the exception that might be thrown as a result of some specific condition.




